- name: Déploiement de l'application Angular
  hosts: all
  become: yes
  vars:
    app_name: aurorefis-frontend
    app_image_name: aurorefis-frontend-image
    app_container_name: aurorefis-frontend-container
    deploy_dir: /var/www/{{ app_name }}
  tasks:
    - name: Vérification de la présence de Node.js
      command: node -v
      register: node_check
      ignore_errors: true

    - name: "Installation de Node.js"
      apt:
        name: nodejs
        state: present

    - name: Installation de npm
      apt:
        name: npm
        state: present
    
    - name: "Copie du projet"
      copy:
        src: /home/test-ansible/aurorefis-frontend
        dest: /var/www/

    - name: Installation des dépendances npm
      command: npm install --force
      args:
        chdir: "{{ deploy_dir }}"

    - name: Compilation de l'application Angular
      command: ng build --prod
      args:
        chdir: "{{ deploy_dir }}"

    - name: Créer une image Docker pour l'application
      docker_image:
        name: "{{ app_image_name }}"
        path: "{{ deploy_dir }}"
        state: present

    - name: Démarrer un nouveau conteneur Docker pour l'application
      docker_container:
        name: "{{ app_container_name }}"
        image: "{{ app_image_name }}"
        state: started
        published_ports:
          - "4300:80"
        volumes:
          - "{{ deploy_dir }}/dist:/usr/share/nginx/html"

    - name: Ajouter Nginx à ufw
      ufw:
        rule: "allow 'Nginx HTTP'"
